### ISSUE TITLE
Errore compilazione

### ISSUE THREAD

**Issue by almanfu** [emanuelenardi/moodle-reti#1]
<s>`texlive-full` dalla versione `2019.XXX` non contiene più il package `enumitem`.
Deve essere installato con:
tlmgr init-usertree
tlmgr install enumitem
</s>
In ogni caso, file compilati l' 08 Agosto 2022:
[quiz-draft.pdf](https://github.com/emanuelenardi/moodle-reti/files/9280918/quiz-draft.pdf)
[quiz-answers.pdf](https://github.com/emanuelenardi/moodle-reti/files/9280919/quiz-answers.pdf)

**Comment by emanuelenardi** [comment]
Ciao Alessandro! 👋

Non mi risulta che il pacchetto `enumitem` non sia più installato di default nella distribuzione di `texlive-full`.

Puoi aiutarmi a riprodurre l'errore di compilazione in cui ti sei imbattuto?

**Comment by almanfu** [comment]
Ciao Emanuele. Si [effettivamente](https://packages.ubuntu.com/focal/all/texlive-latex-extra/filelist) c'è, anche nella repo che ho usato.
Probabilmente ho avuto sfortuna ([e non sarei il primo](https://tex.stackexchange.com/questions/478914/texlive-upgrade-and-missing-packages):open_mouth:).
Grazie comunque
